server:
  port: 8080
  servlet:
    context-path: /pro
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.88.128:61616
    pool:
      enabled: false
      max-connections: 10

queueName: publish.queue
topicName: publish.topic
